### ISSUE TITLE
Support for string or template in secondary-info field

### ISSUE THREAD

**Issue by luixal** [rianadon/timer-bar-card#100]
Hi,

I'm just playing around with the mushroom style config, this in particular:

> primary_info and secondary_info can be any of name, state, last-changed, last-updated, or none to change the information shown on the card.

It would be great to set a custom string or template in `primary_info` and `secondary_info`, just like the mushroom template card does. You could use jinja tamplates an also js template if you wrap this card into a button-card one :)

Cheers!

**Comment by rianadon** [comment]
Seems very reasonable. I'm thinking of adding `primary_text` and `secondary_text` that would override `primary_info` and `secondary_info`. You would be able to set these to any text you like.

**Comment by luixal** [comment]
I'm not sure I understood you well. Do you mean adding two new fields?

One for text/template and another one as is now?

**Comment by rianadon** [comment]
Closing this since as of next update there will be a way to do this using existing fields.

You can use `name` to override what displays in the primary info, and overriding `format` will change what's displayed where the time goes. If you need templates, you can wrap the timer bar card in a template card.

I also realized I misunderstood what you wrote. I based the configuration of the mushroom card on the mushroom entity card, not the mushroom template card. Therefore the behaviors are not going to match that of the template card. That said, I give instructions for combining the card with a template card, so you can still use templates that way.
