### ISSUE TITLE
HomeWhiz Washer/Dryer - Duration vs Remaining

### ISSUE THREAD

**Issue by n00bcodr** [rianadon/timer-bar-card#109]
I have a HomeWhiz compatible Washer and am wondering how to implement it in the bar.

It gives two entities, duration and remaining time. The time is in minutes.

**sensor.bob_duration**

![image](https://github.com/rianadon/timer-bar-card/assets/49611451/28161065-e6de-484f-9049-c5bf4e434281)

**sensor.bob_remaining**

![image](https://github.com/rianadon/timer-bar-card/assets/49611451/4017e609-eec0-4970-972c-141353b8a06e)

PS: Yes, my washer is called Bob 😄

**Comment by rianadon** [comment]
Hi there!

If you have access to the times Bob starts and finishes :), I recommend you use these values plus the duration to specify the time. Otherwise, you can use remaining time. The [section on remaining time](https://github.com/rianadon/timer-bar-card?tab=readme-ov-file#-working-with-new-integrations) in the README explains what values you'll need to pair with the remaining time.

**Comment by GigiPompieru** [comment]
Hey, did you get this working? I have a Beko washing machine and I'm trying to get the card working but I'm not sure if I need to create a custom sensor or just use the info in the card.

So far my progress is:
```
type: custom:timer-bar-card
debug: true
entities:
  - entity: sensor.izaura_remaining_time
    active_state: sensor.izaura_state
    duration:
      attribute: timespan
      units: minutes
```
but the card looks like this:
![image](https://github.com/rianadon/timer-bar-card/assets/28728401/5162c315-efca-4112-9537-5a84d0c16649)
Don't really know what is needed to make the bar appear.

If it helps in anyway, the device exposes:
![image](https://github.com/rianadon/timer-bar-card/assets/28728401/5adbc002-1c8e-4d70-a7ca-6b713ca2559a)

The duration changes based on the program selected and the remaining time remains 1 even if the state goes to off.

**Comment by rianadon** [comment]
@GigiPompieru I'm a bit confused looking at your current config. You have:
```yaml
    duration:
      attribute: timespan
```
but the debug information in the card is showing that the `sensor.izaura_remaining_time` entity doesn't have any `timespan` attribute. Maybe you meant to use `state: true` to set from the entity's state?

Thanks for posting all the entities by the way! This is how I'd set up the card with them:

```yaml
type: custom:timer-bar-card
debug: true
entities:
  - entity: sensor.izaura_state
    active_state: on
    duration:
      entity: sensor.izura_duration
    remaining:
      entity: sensor.izura_remaining_time
      units: minutes
```

**Comment by GigiPompieru** [comment]
this got it working
``
type: custom:timer-bar-card
entities:
  - entity: sensor.izaura_state
    active_state: device_state_running
    duration:
      entity: sensor.izaura_duration
      units: minutes
    remaining:
      entity: sensor.izaura_remaining_time
      units: minutes
 ``

**Comment by rianadon** [comment]
Nice job! That does look like it is working. If you'd like to create an [integration doc](https://github.com/rianadon/timer-bar-card/issues/new?assignees=&labels=integration+doc&projects=&template=tell-me-about-an-integration-you-got-working.md&title=) and copy paste your card configuration & screenshots, I can add it to the README to help anyone else with a HomeWhiz device.

I'll close this issue since you have a successful configuration. @n00bcodr here's your answer 😁
