### ISSUE TITLE
Add show_emtpy option

### ISSUE THREAD

**Issue by PablaV** [rianadon/timer-bar-card#50]
Is it possible to add a show_empty option? I use the progress bar card to show which zones of OpenSprinkler are watering, but would like the card to show up even when it's empty. Basically the exact same option/behaviour as the filter_card default in HA.

**Comment by rianadon** [comment]
I'm a bit confused what you are asking. By default the card should always show the entity you configure it for. And if you provide a title and use `filter: true`, the title should still show even when there are no entities to display. Could you explain more what you're looking for?

Also since you are using OpenSprinkler, I must plug my [OpenSprinkler card](https://github.com/rianadon/opensprinkler-card) in case you haven't seen it :)

**Comment by Hannah-Bee** [comment]
Maybe PablaV means a timer bar that does not totally disappear when remaining time = 0

**Comment by PablaV** [comment]
What I meant was to have some sort of text saying "No Zones Watering" when all zones are off so it just doesn't show blank. Hope that makes sense!

**Comment by rianadon** [comment]
Thank you @PablaV! I understand better now what you're suggesting.

I'm imagining a `show_empty` option would take in a string of text to display if there are no entities to display? So in your case you could say `show_empty: "No Zones Watering"`?

**Comment by PablaV** [comment]
Yes exactly what I mean!

**Comment by rianadon** [comment]
Great! I've pushed the option in version 1.21.
