### ISSUE TITLE
Hydrawise Support

### ISSUE THREAD

**Issue by Buckeyes1995** [rianadon/timer-bar-card#55]
Hello,

Love your card!   Do you have a suggestion or know how to use it with your card?

The Hydrawise integration returns a sensor entity with the time remining on the watering.  I believe I have to use a timer entity for the card?

The only other entities it returns is a binary sensor if it is watering, and the next watering cycle timestamp.

Thanks!

**Comment by rianadon** [comment]
It's going to be a bit difficult at the moment, but once I merge https://github.com/rianadon/timer-bar-card/pull/47 there will be support for using the entity's time remaining to create the card!

**Comment by rianadon** [comment]
Now that #47 is merged, there should be a way to configure the card with Hydrawise. Something like `remain_time: { entity: ... }` should work.

I'll close this for now, and please add to the list of integrations if you are able to make the card work.
Otherwise, please reopen the issue and I'll take a further look.

**Comment by djsomi** [comment]
Did you guys manage to work this one?
