### ISSUE TITLE
Erroneous sync issue alerts

### ISSUE THREAD

**Issue by clinta** [rianadon/timer-bar-card#69]
I've got sync-issue alerts on android using this card. I've checked NTP and date sync, and my clocks are all synced up. The alerts indicate that the clock is over 100,000 seconds off, but this is definitely not true. I do not see these alerts in the web interface, only homeassistant on android.

**Comment by rianadon** [comment]
That's quite a lot of seconds off. Is there a chance that this period of time > 100,000 seconds matches up with when the timer was last triggered? Perhaps the card is thinking the timer was turned on when it was really not.

I attempted to get the sync issues message to show on my home assistant android app, but I was not able to.

**Comment by el97** [comment]
This can't be right... Don't mind the text though
![Sync issue with time](https://user-images.githubusercontent.com/23169868/212457149-0dec6e65-7036-40b8-b7ba-15cc56ac08b1.png)

**Comment by rianadon** [comment]
I wonder if the core of this issue is leaving the Android app open. Perhaps there's some updates to the card which are intentionally delayed being sent until the app is reopened. The card would mistakenly interpret this delay as a misconfigured clock.

The best solution I can come up with to fix this is to require two sync issues in a row to show the alert. It would take longer to see an alert in case of a truly misconfigured clock, but they would pop up less often in cases like these.

**Comment by adam-cobb** [comment]
Yeah it's probably quite a bit less than an hour before it appears to be honest, i've not timed it though. The above is just via a desktop web browser btw, it's just as common on there as the Android app for me.

**Comment by rianadon** [comment]
Please try v1.25. There should be fewer false messages now :)
