### ISSUE TITLE
Cosmetic - Bar is too close to remaining time when in hours

### ISSUE THREAD

**Issue by davidlb** [rianadon/timer-bar-card#72]
When remining time is with hours, the bar is too close. It would nicer with a margin in between.

![2023-02-02 13_45_32-Window](https://user-images.githubusercontent.com/12050155/216329542-ca76d054-02ec-4f14-b680-c7c5a26bf622.png)

**Comment by rianadon** [comment]
Try setting the `text_width` option to something like `6em`. That will give the text a little more air to breath.

As for making this adjustment automatic, I'm not so sure how I could do that (maybe fetch the history of the timer and see if it ever ran over 1 hour?). I prefer to make the text width a constant value rather than something that changes based on how much time is left on the timer. That way, if you have multiple timers on the page, they will all have the same width no matter what the difference in time remaining is.

**Comment by davidlb** [comment]
Thanks, it did the trick!
