### ISSUE TITLE
Mushroom custom color in off state

### ISSUE THREAD

**Issue by sippeeey** [rianadon/timer-bar-card#88]
Is it possible to customize the color from the card when the entity is in off state?

In this screenshot i made, there is an example from my other standard mushroom cards (in the second row).
![image](https://github.com/rianadon/timer-bar-card/assets/38763652/ac05a8ae-945c-4655-ae35-1a7986f4d989)

**Comment by rianadon** [comment]
It would be difficult to make this very customizable since I'm relying on the card from mushroom cards to compute the colors (and I'd like to keep this code as close as possible to mushroom so it's easy to update in the future.

What I can do however is fix the bug so it appears the same as the other mushroom cards. There's a flag for telling the mushroom cards that dark mode is turned on that I did not include.
