### ISSUE TITLE
Support for Rachio irrigation component

### ISSUE THREAD

**Issue by chriswood1001** [rianadon/timer-bar-card#97]
The native [Rachio integration](https://www.home-assistant.io/integrations/rachio/) exposes irrigation timers as a switch with duration as an attribute. When a watering timer begins, the switch turns on and the length is stored as attribute "Duration" in the format "33 minutes", "90 minutes", etc.

Can Rachio be added as a no extra configuration required type, similar to OpenSprinkler and RainMachine? Else, is there a way to leverage a template to extract "90 minutes" into a format supported timer-bar-card?

**Comment by rianadon** [comment]
I forgot to comment on this, but v1.29.1 should have addressed the issues with duration being stored in the format `33 minutes`.

If the duration attribute is named `duration`, then the card should need no extra configuration. However if it's `Duration`, you'll need to add some configuration as the attributes are case-sensitive.

**Comment by rianadon** [comment]
I'm going to close this since I'm assuming you've gotten the integration working. If you indeed have, it would be extra amazing if you could [submit your configuration for Rachio](https://github.com/rianadon/timer-bar-card/issues/new?template=tell-me-about-an-integration-you-got-working.md) so I can add it to the README. Then others using the Rachio integration can easily set up the card. If you haven't managed to get the card working, then please reopen the issue :)
